---
title: "R Notebook"
output: html_notebook
---

##LAB 1 

Se hace stimacion de la ecuaacion 

$$Y=α+β_{X1}X1+β_{X2}X2+u$$

Se trabaja con simulados para poder ver lo que pasa teoricamente 

$$α=5$$
$$β_{X1}=0.5$$
d

##CALCULO DE LA VARIANZA DEL ERROR σ̂


```{r}
uhat<-modelo1$residuals
sigmahat<-(sum(uhat^2))/(modelo1$df.residual)#Varianza estimada del error
sigmacuadradao
X1bar<-mean(dfs$X1)
sumX1sqr<-sum((dfs$X1-X1bar)^2)


```


##TOCA HACER LA REGRESION DE LA VARIABLE DE X1 CONTRA X2

```{r}
Rsqrx1<-summary(lm(X1~X2,data=dfs))$r.squared
```

##CONTINUACION DEL CALLCULO DE LA VARIANZA DEL ESTIMADOR 


```{r}
varhatb1hat<-sigmahat/(sumX1sqr*(1-Rsqrx1))#Varianza estimada del estimador
varhatb1hat
```

##SE SACA EL ERROR ESTANDAR 

```{r}
se=varhatb1hat^(1/2)
t<-coef(modelo1)[2]/se
t
```
```{r}
funcShaded <- function(x) {
  y <- dt(x,df=87)
  y[x > -2&x<2 ] <- NA
  return(y)
}
library(ggplot2)
tdst<- ggplot(data.frame(x = c(-4, 4)), aes(x = x)) +
  stat_function(fun = dt, args = list(df = modelo1$df.residual))
tdst+theme_classic()+stat_function(fun=funcShaded,geom="area", fill="blue",alpha=0.2)+
  annotate("text", x =-3 , y = 0.1,label="Area=0.25")+annotate("text", x =3 , y = 0.1,label="Area=0.25")+
labs(title="Zonas de rechazo al 5%, df=60",y="",x="")
```



```{r}

library(mvtnorm)
N=10000
coefs<-cbind("hat_beta_1" = numeric(1000)) #Vector que guardará los coeficientes
set.seed(1) # permite reproducir los resultados
X <- rmvnorm(N, c(500,100), sigma = cbind(c(10, 2.5), c(2.5, 10))) # generamos X1 y X2
u <- rnorm(N, sd = 5)
Y <- 5 + 0.5 * X[, 1] + u

xdf<-data.frame(X,Y)
dfs<-sample(c(TRUE,FALSE),nrow(xdf),replace=TRUE,prob=c(0.01,0.99)) #muestra aleatoria, n aprox 100
dfs<-xdf[dfs,]

modelo1=lm(Y~X1,data=dfs)
modelo1

summary(modelo1)


`
```



